<?php

declare(strict_types=1);

namespace Emontis\FitReader\Codegen;

use Emontis\FitReader\Protocol\BaseType;

/**
 * Reads Garmin's Profile.xlsx and emits two generated PHP files:
 *
 *   - MessageDefinitions.php  → array<int, MessageDef> keyed by global msg num
 *   - Types.php               → array<string, array<int, string>>  typeName → value → label
 */
final class ProfileGenerator
{
    /** Underlying base type per FIT named type. */
    private array $typeBase = [];

    /** typeName → [value => label] */
    private array $typeValues = [];

    /** messages: messageName → [fieldDefNum => FieldRow] */
    private array $messages = [];

    public function __construct(private readonly string $xlsxPath)
    {
    }

    public function generate(string $outDir): void
    {
        $reader = new XlsxReader($this->xlsxPath);
        $this->loadTypes($reader->sheet('Types'));
        $this->loadMessages($reader->sheet('Messages'));
        $reader->close();

        $mesgNumMap = $this->typeValues['mesg_num'] ?? [];
        if ($mesgNumMap === []) {
            throw new \RuntimeException('Profile.xlsx Types sheet has no mesg_num type — cannot map message names to global numbers');
        }
        // Invert: messageName → globalNum
        $messageNameToGlobal = [];
        foreach ($mesgNumMap as $value => $name) {
            $messageNameToGlobal[$name] = $value;
        }

        $messagesPhp = $this->emitMessages($messageNameToGlobal);
        $typesPhp    = $this->emitTypes();

        file_put_contents($outDir . '/MessageDefinitions.php', $messagesPhp);
        file_put_contents($outDir . '/Types.php', $typesPhp);
    }

    /** @param array<int, array<int, string>> $rows */
    private function loadTypes(array $rows): void
    {
        $currentType = null;
        // skip header row 0
        for ($i = 1; $i < count($rows); $i++) {
            $r = $rows[$i];
            $typeName = trim($r[0] ?? '');
            $baseType = trim($r[1] ?? '');
            $valName  = trim($r[2] ?? '');
            $valRaw   = trim($r[3] ?? '');

            if ($typeName !== '') {
                $currentType                = $typeName;
                $this->typeBase[$typeName]  = $baseType;
                $this->typeValues[$typeName] = $this->typeValues[$typeName] ?? [];
                continue;
            }

            if ($currentType === null || $valName === '' || $valRaw === '') {
                continue;
            }
            $intVal = self::parseInt($valRaw);
            if ($intVal === null) {
                continue;
            }
            $this->typeValues[$currentType][$intVal] = $valName;
        }
    }

    /** @param array<int, array<int, string>> $rows */
    private function loadMessages(array $rows): void
    {
        $currentMessage = null;
        for ($i = 1; $i < count($rows); $i++) {
            $r       = $rows[$i];
            $msgName = trim($r[0] ?? '');
            $fieldDefRaw = trim($r[1] ?? '');
            $fieldName   = trim($r[2] ?? '');
            $fieldType   = trim($r[3] ?? '');
            $scale       = trim($r[6] ?? '');
            $offset      = trim($r[7] ?? '');
            $units       = trim($r[8] ?? '');

            if ($msgName !== '') {
                $currentMessage = $msgName;
                $this->messages[$msgName] = $this->messages[$msgName] ?? [];
                continue;
            }

            if ($currentMessage === null || $fieldDefRaw === '' || $fieldName === '') {
                // sub-field rows (empty fieldDefNum) — skipped for now
                continue;
            }
            $defNum = self::parseInt($fieldDefRaw);
            if ($defNum === null) {
                continue;
            }
            $this->messages[$currentMessage][$defNum] = [
                'fieldDefNum' => $defNum,
                'name'        => $fieldName,
                'fieldType'   => $fieldType,
                'scale'       => $scale,
                'offset'      => $offset,
                'units'       => $units,
            ];
        }
    }

    private function emitMessages(array $messageNameToGlobal): string
    {
        $out = "<?php\n\n// Generated by bin/generate-profile from resources/Profile.xlsx.\n// Do not edit by hand.\n\n";
        $out .= "declare(strict_types=1);\n\n";
        $out .= "use Emontis\\FitReader\\Profile\\FieldDef;\n";
        $out .= "use Emontis\\FitReader\\Profile\\MessageDef;\n";
        $out .= "use Emontis\\FitReader\\Protocol\\BaseType;\n\n";
        $out .= "return [\n";

        ksort($this->messages);
        $emitted = 0;
        foreach ($this->messages as $msgName => $fields) {
            $globalNum = $messageNameToGlobal[$msgName] ?? null;
            if ($globalNum === null) {
                continue; // not registered in mesg_num
            }
            $out .= sprintf("    %d => new MessageDef(%d, %s, [\n",
                $globalNum, $globalNum, var_export($msgName, true));
            ksort($fields);
            foreach ($fields as $f) {
                $baseType = $this->resolveBaseType($f['fieldType']);
                if ($baseType === null) {
                    continue; // skip fields whose type doesn't resolve
                }
                $scale  = self::parseFloatFirst($f['scale']) ?? 1.0;
                $offset = self::parseFloatFirst($f['offset']) ?? 0.0;
                $units  = $f['units'] !== '' ? $f['units'] : null;
                $typeName = $this->isNamedType($f['fieldType']) ? $f['fieldType'] : null;

                $out .= sprintf("        %d => new FieldDef(%d, %s, %s, %s, %s, %s, %s),\n",
                    $f['fieldDefNum'],
                    $f['fieldDefNum'],
                    var_export($f['name'], true),
                    'BaseType::' . $baseType->name,
                    self::numLit($scale),
                    self::numLit($offset),
                    $units === null ? 'null' : var_export($units, true),
                    $typeName === null ? 'null' : var_export($typeName, true),
                );
            }
            $out .= "    ]),\n";
            $emitted++;
        }
        $out .= "];\n";
        fwrite(STDERR, "  messages emitted: {$emitted}\n");
        return $out;
    }

    private function emitTypes(): string
    {
        $out  = "<?php\n\n// Generated by bin/generate-profile from resources/Profile.xlsx.\n// Do not edit by hand.\n\n";
        $out .= "declare(strict_types=1);\n\n";
        $out .= "return [\n";
        ksort($this->typeValues);
        $count = 0;
        foreach ($this->typeValues as $name => $values) {
            if ($values === []) continue;
            $out .= '    ' . var_export($name, true) . " => [\n";
            ksort($values);
            foreach ($values as $v => $label) {
                $out .= "        {$v} => " . var_export($label, true) . ",\n";
            }
            $out .= "    ],\n";
            $count++;
        }
        $out .= "];\n";
        fwrite(STDERR, "  types emitted: {$count}\n");
        return $out;
    }

    /**
     * Resolve a Profile "Field Type" string to a BaseType:
     *  - direct base-type name (e.g. "uint16")
     *  - named profile type whose underlying base type is something we know
     */
    private function resolveBaseType(string $fieldType): ?BaseType
    {
        if ($fieldType === '') {
            return null;
        }
        $direct = self::baseTypeByName($fieldType);
        if ($direct !== null) {
            return $direct;
        }
        $underlying = $this->typeBase[$fieldType] ?? null;
        if ($underlying === null) {
            return null;
        }
        return self::baseTypeByName($underlying);
    }

    private function isNamedType(string $fieldType): bool
    {
        return $fieldType !== '' && self::baseTypeByName($fieldType) === null && isset($this->typeBase[$fieldType]);
    }

    private static function baseTypeByName(string $name): ?BaseType
    {
        return match ($name) {
            'enum'    => BaseType::Enum,
            'sint8'   => BaseType::Sint8,
            'uint8'   => BaseType::Uint8,
            'sint16'  => BaseType::Sint16,
            'uint16'  => BaseType::Uint16,
            'sint32'  => BaseType::Sint32,
            'uint32'  => BaseType::Uint32,
            'string'  => BaseType::String,
            'float32' => BaseType::Float32,
            'float64' => BaseType::Float64,
            'uint8z'  => BaseType::Uint8z,
            'uint16z' => BaseType::Uint16z,
            'uint32z' => BaseType::Uint32z,
            'byte'    => BaseType::Byte,
            'sint64'  => BaseType::Sint64,
            'uint64'  => BaseType::Uint64,
            'uint64z' => BaseType::Uint64z,
            default   => null,
        };
    }

    private static function parseInt(string $raw): ?int
    {
        $raw = trim($raw);
        if ($raw === '') return null;
        if (str_starts_with($raw, '0x') || str_starts_with($raw, '0X')) {
            return (int) hexdec(substr($raw, 2));
        }
        if (ctype_digit($raw) || ($raw[0] === '-' && ctype_digit(substr($raw, 1)))) {
            return (int) $raw;
        }
        // Garmin XLSX numbers sometimes come through as "1.0"
        if (is_numeric($raw)) {
            $f = (float) $raw;
            if ($f === floor($f) && abs($f) < PHP_INT_MAX) {
                return (int) $f;
            }
        }
        return null;
    }

    private static function parseFloatFirst(string $raw): ?float
    {
        $raw = trim($raw);
        if ($raw === '') return null;
        // Component-field values look like "100,1,4" — take the first.
        if (str_contains($raw, ',')) {
            $raw = trim(explode(',', $raw)[0]);
        }
        if (!is_numeric($raw)) return null;
        return (float) $raw;
    }

    private static function numLit(float $f): string
    {
        if ($f === floor($f) && abs($f) < 1e15) {
            return ((int) $f) . '.0';
        }
        return var_export($f, true);
    }
}
